name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build (GCC)
      if: matrix.os != 'windows'
      run: ./mk
    - uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows'
    - name: Build (Windows)
      if: matrix.os == 'windows'
      shell: cmd
      run: mk.bat
    - name: Zip (Linux, macOS)
      if: matrix.os != 'windows'
      run: zip fart-${{ matrix.os }}.zip fart
    - name: Zip (Windows)
      if: matrix.os == 'windows'
      run: Compress-Archive -Path fart.exe -Destination fart-${{ matrix.os }}.zip
    - name: Upload Fart Packages to Release
      uses: softprops/action-gh-release@master
      with:
        files: |
          /home/runner/work/fart-it/fart-it/*.zip
          
        name: Fart it
        tag_name: ${{ github.run_id }}
